// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiloManager.Infrastructure.Data;

#nullable disable

namespace SiloManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715172930_AddGrauSecador")]
    partial class AddGrauSecador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SiloManager.Domain.Entities.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervaloMinimoSegundos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(900);

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique();

                    b.ToTable("Configuracoes", (string)null);
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("BaudRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(9600);

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortaCOM")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Equipamentos", (string)null);
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Medicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DadosBrutosSerial")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraEquipamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraSistema")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("GrauSecador")
                        .HasColumnType("REAL");

                    b.Property<int?>("IntervaloSegundos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetrabalho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiloDestinoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Umidade")
                        .HasColumnType("REAL");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("SecadorId");

                    b.HasIndex("SiloDestinoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Medicoes", (string)null);
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("UmidadeMaxima")
                        .HasColumnType("REAL");

                    b.Property<double>("UmidadeMinima")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Secador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Secadores", (string)null);
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Silo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetrabalho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Silos", (string)null);
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Login")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Configuracao", b =>
                {
                    b.HasOne("SiloManager.Domain.Entities.Empresa", "Empresa")
                        .WithOne("Configuracao")
                        .HasForeignKey("SiloManager.Domain.Entities.Configuracao", "EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Equipamento", b =>
                {
                    b.HasOne("SiloManager.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Equipamentos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Medicao", b =>
                {
                    b.HasOne("SiloManager.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Medicoes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiloManager.Domain.Entities.Equipamento", "Equipamento")
                        .WithMany("Medicoes")
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiloManager.Domain.Entities.Produto", "Produto")
                        .WithMany("Medicoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiloManager.Domain.Entities.Secador", "Secador")
                        .WithMany("Medicoes")
                        .HasForeignKey("SecadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SiloManager.Domain.Entities.Silo", "SiloDestino")
                        .WithMany("Medicoes")
                        .HasForeignKey("SiloDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiloManager.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Medicoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Equipamento");

                    b.Navigation("Produto");

                    b.Navigation("Secador");

                    b.Navigation("SiloDestino");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Secador", b =>
                {
                    b.HasOne("SiloManager.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Secadores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Silo", b =>
                {
                    b.HasOne("SiloManager.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Silos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiloManager.Domain.Entities.Produto", "Produto")
                        .WithMany("Silos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SiloManager.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Configuracao");

                    b.Navigation("Equipamentos");

                    b.Navigation("Medicoes");

                    b.Navigation("Secadores");

                    b.Navigation("Silos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Equipamento", b =>
                {
                    b.Navigation("Medicoes");
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Medicoes");

                    b.Navigation("Silos");
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Secador", b =>
                {
                    b.Navigation("Medicoes");
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Silo", b =>
                {
                    b.Navigation("Medicoes");
                });

            modelBuilder.Entity("SiloManager.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Medicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
